POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "bill's blog",
  "author": "bill",
  "url": "https:/olympicbloom",
  "likes": 3,
  "userId": "61e6eb132307e562c351b356"
}